[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
futures = "0.3.27" 
serde_json = "1.0.94"
tensor_lib = {path = "../lib"}
tokio = {version = "1.26.0",  features = ["full"]}

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }

[[bench]]
name = "rolling_holc" 
harness = false 
